# Generated by Django 4.0.3 on 2022-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('cource_num', models.IntegerField(verbose_name='Курс')),
                ('direction', models.CharField(max_length=15, verbose_name='Направление')),
            ],
        ),
    ]
